# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: git push --force
email: rs3vans@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Some of my thoughts about writing software and the constant
  process of pushing myself to become a better software engineer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rs3vans.github.io" # the base hostname & protocol for your site
twitter_username: rs3vans
github_username:  rs3vans

# Build settings
markdown: kramdown
